# -*- coding: utf-8 -*-
"""coloración dual prueba 1ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19UXz9CJuqO6N5Rl7dPoBdMObQycBriYw
"""

import streamlit as st
from streamlit_agraph import agraph, Node, Edge, Config

# Configuración inicial de la página
st.set_page_config(page_title="Editor de Grafos Arcoíris", layout="wide")

st.title("🌈 Editor Interactivo de Grafos")
st.markdown("""
Usa el panel de la izquierda para construir tu grafo paso a paso.
¡Puedes arrastrar los nodos en el lienzo central para acomodarlos a tu gusto!
""")

# 1. INICIALIZAR LA MEMORIA (Session State)
# Usamos conjuntos y listas para guardar la estructura sin que se borre al dar clic
if 'nodos' not in st.session_state:
    st.session_state.nodos = set(["A", "B", "C"]) # Nodos iniciales por defecto

if 'aristas' not in st.session_state:
    st.session_state.aristas = [
        {"origen": "A", "destino": "B", "color": "#FF4B4B"}, # Rojo
        {"origen": "B", "destino": "C", "color": "#00D4FF"}, # Azul
    ]

# 2. PANEL DE CONTROL (Barra Lateral izquierda)
with st.sidebar:
    st.header("🛠️ Controles del Grafo")

    # --- Sección: Agregar Nodos ---
    st.subheader("1. Agregar Nodo")
    nuevo_nodo = st.text_input("Nombre del nuevo nodo (Ej: D, E, F):", value="").strip().upper()
    if st.button("➕ Crear Nodo"):
        if nuevo_nodo and nuevo_nodo not in st.session_state.nodos:
            st.session_state.nodos.add(nuevo_nodo)
            st.success(f"Nodo '{nuevo_nodo}' agregado.")
            st.rerun()
        elif nuevo_nodo in st.session_state.nodos:
            st.warning("Ese nodo ya existe.")

    st.divider()

    # --- Sección: Agregar Aristas Coloreadas ---
    st.subheader("2. Conectar Nodos con Color")
    if len(st.session_state.nodos) >= 2:
        lista_nodos = sorted(list(st.session_state.nodos))

        origen = st.selectbox("Desde el nodo:", lista_nodos, key="origen")
        destino = st.selectbox("Hacia el nodo:", lista_nodos, key="destino")
        color_elegido = st.color_picker("Elige el color de la arista:", "#00FF66") # Verde por defecto

        if st.button("🔗 Conectar Nodos"):
            if origen == destino:
                st.error("No se permiten bucles (un nodo conectado a sí mismo).")
            else:
                # Evitar duplicados simples reemplazando o ignorando
                nueva_conexion = {"origen": origen, "destino": destino, "color": color_elegido}
                st.session_state.aristas.append(nueva_conexion)
                st.success(f"Conectado {origen} con {destino}")
                st.rerun()
    else:
        st.info("Necesitas al menos 2 nodos para crear conexiones.")

    st.divider()

    # --- Botón para reiniciar todo ---
    if st.button("🗑️ Borrar Todo el Grafo"):
        st.session_state.nodos = set(["A", "B", "C"])
        st.session_state.aristas = [
            {"origen": "A", "destino": "B", "color": "#FF4B4B"},
            {"origen": "B", "destino": "C", "color": "#00D4FF"},
        ]
        st.rerun()

# 3. CONSTRUCCIÓN VISUAL DEL GRAFO (Cuerpo Principal)
col1, col2 = st.columns([3, 1])

with col1:
    st.subheader("🖼️ Lienzo del Grafo")

    # Traducir los datos guardados en memoria a objetos que entiende streamlit-agraph
    nodes_agraph = [Node(id=n, label=n, size=25, color="#EAEAEA") for n in st.session_state.nodos]

    edges_agraph = [
        Edge(source=a["origen"], target=a["destino"], color=a["color"], strokeWidth=4)
        for a in st.session_state.aristas
    ]

    # Configuración estética del lienzo interactivo
    config = Config(
        width=700,
        height=500,
        directed=False, # Grafo no dirigido
        physics=True,   # Habilita el movimiento elástico realista
        hierarchical=False
    )

    # Renderizar el grafo interactivo en pantalla
    agraph(nodes=nodes_agraph, edges=edges_agraph, config=config)

with col2:
    st.subheader("📋 Datos Actuales")
    st.write("**Nodos registrados:**")
    st.write(list(st.session_state.nodos))

    st.write("**Aristas (Conexiones):**")
    for a in st.session_state.aristas:
        st.markdown(f"• {a['origen']} ↔️ {a['destino']} (<span style='color:{a['color']}'>■</span> {a['color']})", unsafe_allow_html=True)